### ISSUE TITLE
Track SMS send failures

### ISSUE THREAD

**Issue by cailyncodes** [ctoec/care-4-kids-auto-notifier#10]
This may be unnecessary at this point, but it will probably be valuable to update our database with a confirmation from Twilio that the SMS was sent. It will allow us to manually re-send failed notifications and otherwise analyze the data.

Relatedly, it might make sense to include a `caseid` to track which families were notified (as opposed to only having the message text stored).

**Comment by geramirez** [comment]
Should we prioritize this if we don't have extra work?

**Comment by cailyncodes** [comment]
I would say yes, depending on if we get DB access today and how the dry run goes

**Comment by mmazanec22** [comment]
Originally this issue was called "Add `did_send` and `caseid` to Notification schema"

**Comment by cailyncodes** [comment]
Closed by #53
