### ISSUE TITLE
US # 1 Pilot Enrollment Confirmation

### ISSUE THREAD

**Issue by alvordg** [ctoec/care-4-kids-auto-notifier#26]
US ID # 1
As a Pilot Participant, I want to be notified, so that I can know that I am enrolled.

Acceptance Criteria 

1.  When a participant texts CONFIRM to Skylight to confirm participation
2.  THEN Skylight receives CONFIRM text and the system checks that it is from an invited participant 
3.  AND THEN the system sends the Welcome text to the Participant
4.  AND THEN a Participant receives the Welcome Text

**Comment by geramirez** [comment]
I think we are done with this, @cailyncodes. It looks like the email list doesn't work correctly, but that's a detail we can change later.

**Comment by cailyncodes** [comment]
👍 for being done (pending UW's thoughts on Twilio Studio vs TextIt)

**Comment by geramirez** [comment]
@mmazanec22 Hey, I'm closing this since you noted it was done on Twilio
