### ISSUE TITLE
US # 2 Pilot Participant Does Not Confirm Enrollment in Pilot

### ISSUE THREAD

**Issue by alvordg** [ctoec/care-4-kids-auto-notifier#27]
US ID # 2
As a Pilot Participant, I want to be able to notify Skylight, that I do not want to enroll in the pilot.

Acceptance Criteria 

1.  When a participant texts NO to Skylight 
2.  THEN Skylight receives NO text
3.   AND THEN Skylight does not add the participant to the Tracker Worksheet
4.  AND THEN Skylight sends a Text thanking the Participant for their time and confirms no participation in pilot
5.  AND THEN a Participant receives the text from Skylight thanking them for their time and confirming no participation in pilot

**Comment by mmazanec22** [comment]
This issue is handled in Twilio Studio
