### ISSUE TITLE
US # 3  Participant Texts ASK QUESTION

### ISSUE THREAD

**Issue by alvordg** [ctoec/care-4-kids-auto-notifier#29]
As a Pilot Participant, I want to text ASK QUESTION to access the link to share my comments, provide feedback on the notifications or ask questions about my redetermination.

Acceptance Criteria
When a participant texts ASK QUESTION via text to Skylight 
AND Skylight receives ASK QUESTION text
THEN the system sends a text with the link to the on-line survey and hotline # 1-888-214-5437 for questions/concerns regarding C4K redetermination
AND THEN if issue is a defect, Skylight Team adds to backlog for DEV Team to fix

**Comment by alvordg** [comment]
Draft of message:
“Do you have questions or feedback about the notifications you’ve been receiving? Please share your comments via this link: http://bit.ly/Care4KidsPilot. If you require a response, a member of our team will get back to you as soon as possible. For all questions regarding your Care 4 Kids application, please call Care 4 Kids at 1-888-214-5437.”

**Comment by mmazanec22** [comment]
This issue is handled in Twilio Studio for the pilot.  If we want to include something like this long term maybe that's something to revisit after?
