### ISSUE TITLE
US#4 Participant texts REMOVE ME to end Pilot Participation

### ISSUE THREAD

**Issue by alvordg** [ctoec/care-4-kids-auto-notifier#30]
As a Pilot Participant, I want to text REMOVE ME to Skylight to end my participation in the pilot 

Acceptance Criteria
When a participant texts REMOVE ME via text to Skylight
THEN Skylight receives REMOVE ME text
AND THEN Skylight updates the Tracker spreadsheet to remove participant from pilot
AND THEN  DEV Team updates database to remove participant from pilot
AND THEN Skylight sends a confirmation message to the participant that they have been removed from the pilot

**Comment by geramirez** [comment]
@mmazanec22, I think you finished this earlier, right? If so we should meet up with @alvordg after standup to review the feature and make sure it does what she intended.

**Comment by alvordg** [comment]
Sample message:
“Thank you for your participation in the Care 4 Kids notifications pilot program! You will no longer receive text notifications about your redetermination. To rejoin, or to provide feedback regarding the notifications you have received, please use this link: http://bit.ly/Care4KidsPilot.”

**Comment by mmazanec22** [comment]
This is handled in Twilio Studio
