### ISSUE TITLE
US # 5 Text STATUS to Receive Dates For Redeterminations Currently Being Processed 

### ISSUE THREAD

**Issue by alvordg** [ctoec/care-4-kids-auto-notifier#31]
Acceptance Criteria
When a participant texts STATUS via text to Skylight
THEN Skylight receives STATUS text
AND THEN Skylight sends an automated text with dates of redeterminations currently being processed
AND THEN participants are aware of dates of redeterminations currently being processed

**Comment by cailyncodes** [comment]
From Leo: "We get a report from ImpaCT, however it would not be possible to automate from that report since it contains items that are hung up and have to be ignored to get a true date (human filtering in applied)."

It looks like we might need to do web scraping?
