### ISSUE TITLE
US # 7 Send Text When a New Document is Indexed

### ISSUE THREAD

**Issue by alvordg** [ctoec/care-4-kids-auto-notifier#33]
As the system, it wants to be notified when a new document is indexed in DocuClass so it can automatically send a text to the Participant confirming receipt of a new document

Acceptance Criteria
The system automatically checks periodically when the new document is indexed in DocuClass
AND THEN confirms Participant participation in the pilot
AND THEN automatically triggers a "Document Received" text to confirmed pilot participants
AND THEN the Participant receives the "Document Received" text

**Comment by geramirez** [comment]
We have the walking skeleton for this but we need to set up the correct messages.
