### ISSUE TITLE
Chore: update unitedway fake database schema

### ISSUE THREAD

**Issue by geramirez** [ctoec/care-4-kids-auto-notifier#34]
I figured we could add a category for chores, @alvordg. These would not be user stories rather tasks that we complete to bring down technical debt or prepare us to move faster in the future. 

If we were tracking our velocity chores would not be counted. 

Acceptance Criteria:
Use the same table names as the excel spreadsheet. 
```
ClientID    ReceivedDate    CallerID    ExportDate    ExportTime    Source    DocType    DocID
```

**Comment by mmazanec22** [comment]
PR #38 should handle this chore
