### ISSUE TITLE
Handle SMS delivery fails-- need to notify someone for trial

### ISSUE THREAD

**Issue by mmazanec22** [ctoec/care-4-kids-auto-notifier#46]

**Comment by cailyncodes** [comment]
This would be for both Twilio Studio flows and the document "exported" events, correct?

Did y'all discuss how to notify the parent?

**Comment by mmazanec22** [comment]
We did not discuss how to notify the parent-- that's a good point that we should raise with our team.  For now, with the Twilio Studio flow, we're just sending an email to our team like we are when someone signs up for the pilot.  I'm not sure how we should do that here since it's a concern that will outlive the pilot-- some ideas that come to mind (in addition to logging it of course) include 1) Sending a message or call to the backup number 2) Sending an email to the parent 3) Notifying UW via email.
